services:
  # Frontend (Next.js) - Deploy from client-side folder
  - type: web
    name: junkjet-frontend
    env: node
    region: ohio
    buildCommand: cd client-side && npm install && npm run build
    startCommand: cd client-side && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: http://localhost:8000
    autoDeploy: true
